passed(1,5). % Pasangan koordinat path yang dilalui
passed(0,5). % Pasangan koordinat path yang dilalui
passed(0,4). % Pasangan koordinat path yang dilalui
passed(0,3). % Pasangan koordinat path yang dilalui
passed(0,2). % Pasangan koordinat path yang dilalui
passed(0,3). % Pasangan koordinat path yang dilalui
passed(1,3). % Pasangan koordinat path yang dilalui
passed(2,3). % Pasangan koordinat path yang dilalui
passed(3,3). % Pasangan koordinat path yang dilalui
passed(4,3). % Pasangan koordinat path yang dilalui
passed(4,2). % Pasangan koordinat path yang dilalui
passed(4,3). % Pasangan koordinat path yang dilalui
passed(4,4). % Pasangan koordinat path yang dilalui
passed(4,3). % Pasangan koordinat path yang dilalui
passed(5,3). % Pasangan koordinat path yang dilalui
passed(6,3). % Pasangan koordinat path yang dilalui
passed(6,2). % Pasangan koordinat path yang dilalui
passed(7,2). % Pasangan koordinat path yang dilalui
passed(8,2). % Pasangan koordinat path yang dilalui
passed(8,3). % Pasangan koordinat path yang dilalui
passed(8,4). % Pasangan koordinat path yang dilalui
passed(9,4). % Pasangan koordinat path yang dilalui
passed(10,4). % Pasangan koordinat path yang dilalui
passed(11,4). % Pasangan koordinat path yang dilalui
passed(11,5). % Pasangan koordinat path yang dilalui
passed(11,6). % Pasangan koordinat path yang dilalui
passed(11,7). % Pasangan koordinat path yang dilalui
passed(11,8). % Pasangan koordinat path yang dilalui
passed(11,9). % Pasangan koordinat path yang dilalui
passed(11,10). % Pasangan koordinat path yang dilalui
passed(11,11). % Pasangan koordinat path yang dilalui
passed(10,11). % Pasangan koordinat path yang dilalui
passed(10,12). % Pasangan koordinat path yang dilalui
